### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by murliatdure** [collectmeaustralia/cordova-cloudinary-upload#2]
Any plans for the android support?

**Comment by mablack** [comment]
Hi @murliatdure 

I've been using [cordova-plugin-file-transfer](https://github.com/apache/cordova-plugin-file-transfer) and the [Cloudinary HTTP API](http://cloudinary.com/documentation/upload_images) to get it working on Android as well as iOS, I've included some instructions on issue #1 if you're interested in seeing how it works!

**Comment by murliatdure** [comment]
Hey Thanks,

var upImage = encodedFileData;
    var options = new FileUploadOptions();
    options.fileKey = "file";
    options.fileName = upImage;
    options.file = upImage;
    options.mimeType = "image/jpeg";
    options.chunkedMode = false;
    options.headers = {
        Connection: "close"
    };

```
var params = {};
params.cloud_name = config.cloudinary.cloudName;
params.upload_preset = config.cloudinary.uploadPreset;
options.params = params;

var ft = new FileTransfer();
ft.upload(upImage, encodeURI(config.cloudinary.endPoint), successCallback, failureCallback, options);    
```

The given code snap is working for me too ... on Android, iOS.

I was looking for the support from the given plugin.

**Comment by RasoMrdjenovic** [comment]
Hi, 
Plugin by default is always expecting image, so when you try to upload video you got error, can you extend it by additional parameter which we gonna use to define file type we are uploading?
Tnx
